package earth.terrarium.chipped.datagen.provider.client;

import earth.terrarium.chipped.Chipped;
import earth.terrarium.chipped.common.registry.ModBlocks;
import earth.terrarium.chipped.common.registry.ModItems;
import net.minecraft.data.PackOutput;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.level.block.RedstoneWallTorchBlock;
import net.minecraft.world.level.block.WallSignBlock;
import net.minecraft.world.level.block.WallTorchBlock;
import net.neoforged.neoforge.common.data.LanguageProvider;
import org.codehaus.plexus.util.StringUtils;

import java.util.Objects;

public class ModLangProvider extends LanguageProvider {
    public ModLangProvider(PackOutput pGenerator) {
        super(pGenerator, Chipped.MOD_ID, "en_us");
    }

    @Override
    protected void addTranslations() {
        add("itemGroup.chipped.main", "Chipped");

        ModBlocks.BLOCKS.stream().filter(e -> !(e.get() instanceof WallSignBlock || e.get() instanceof WallTorchBlock || e.get() instanceof RedstoneWallTorchBlock)).forEach(entry -> addBlock(entry, StringUtils.capitaliseAllWords(entry.getId().getPath().replace("_", " "))));
        ModItems.ITEMS.stream().filter(e -> !(e.get() instanceof BlockItem)).forEach(entry -> addItem(entry, StringUtils.capitaliseAllWords(Objects.requireNonNull(entry.getId()).getPath().replace("_", " "))));

        add("container.chipped.botanist_workbench", "Botanist's Workbench");
        add("container.chipped.glassblower", "Glassblower's Workbench");
        add("container.chipped.carpenters_table", "Carpenter's Workbench");
        add("container.chipped.loom_table", "Shepherd's Workbench");
        add("container.chipped.mason_table", "Mason's Workbench");
        add("container.chipped.alchemy_bench", "Alchemy Bench");
        add("container.chipped.tinkering_table", "Tinkering Table");
        add("container.chipped.workbench", "Workbench");

        add("text.chipped.preview", "Preview");
        add("text.chipped.craft", "Craft");
        add("text.chipped.craft_all", "Craft All");
        add("text.chipped.single", "Single");
        add("text.chipped.horizontal", "Horizontal");
        add("text.chipped.vertical", "Vertical");
        add("text.chipped.two_by_two", "Two by Two");

        add("tag.item.chipped.amethyst_block", "Amethyst Blocks");
        add("tag.item.chipped.coal_block", "Coal Blocks");
        add("tag.item.chipped.crying_obsidian", "Crying Obsidian");
        add("tag.item.chipped.lodestone", "Lodestone");
        add("tag.item.chipped.lapis_block", "Lapis Blocks");
        add("tag.item.chipped.diamond_block", "Diamond Blocks");
        add("tag.item.chipped.emerald_block", "Emerald Blocks");
        add("tag.item.chipped.gold_block", "Gold Blocks");
        add("tag.item.chipped.iron_block", "Iron Blocks");
        add("tag.item.chipped.netherite_block", "Netherite Blocks");
        add("tag.item.chipped.sponge", "Sponges");
        add("tag.item.chipped.glowstone", "Glowstone");
        add("tag.item.chipped.waxed_copper_block", "Waxed Copper Block");
        add("tag.item.chipped.waxed_exposed_copper_block", "Waxed Exposed Copper Block");
        add("tag.item.chipped.waxed_weathered_copper", "Waxed Weathered Copper");
        add("tag.item.chipped.waxed_oxidized_copper", "Waxed Oxidized Copper");
        add("tag.item.chipped.blue_ice", "Blue Ice");
        add("tag.item.chipped.dirt", "Dirt");
        add("tag.item.chipped.ice", "Ice");
        add("tag.item.chipped.packed_ice", "Packed Ice");
        add("tag.item.chipped.snow_block", "Snow Blocks");
        add("tag.item.chipped.clay", "Clay");
        add("tag.item.chipped.mud", "Mud");
        add("tag.item.chipped.packed_mud", "Packed Mud");
        add("tag.item.chipped.acacia_leaves", "Acacia Leaves");
        add("tag.item.chipped.birch_leaves", "Birch Leaves");
        add("tag.item.chipped.dark_oak_leaves", "Dark Oak Leaves");
        add("tag.item.chipped.jungle_leaves", "Jungle Leaves");
        add("tag.item.chipped.mangrove_roots", "Mangrove Roots");
        add("tag.item.chipped.oak_leaves", "Oak Leaves");
        add("tag.item.chipped.spruce_leaves", "Spruce Leaves");
        add("tag.item.chipped.ochre_froglight", "Ochre Froglights");
        add("tag.item.chipped.pearlescent_froglight", "Pearlescent Froglights");
        add("tag.item.chipped.verdant_froglight", "Verdant Froglights");
        add("tag.item.chipped.bone_block", "Bone Blocks");
        add("tag.item.chipped.brown_mushroom_block", "Brown Mushroom Blocks");
        add("tag.item.chipped.red_mushroom_block", "Red Mushroom Blocks");
        add("tag.item.chipped.brown_mushroom", "Brown Mushrooms");
        add("tag.item.chipped.red_mushroom", "Red Mushrooms");
        add("tag.item.chipped.cobweb", "Cobwebs");
        add("tag.item.chipped.mushroom_stem", "Mushroom Stems");
        add("tag.item.chipped.gravel", "Gravel");
        add("tag.item.chipped.hay_block", "Hay Blocks");
        add("tag.item.chipped.moss_block", "Moss Blocks");
        add("tag.item.chipped.melon", "Melons");
        add("tag.item.chipped.shroomlight", "Shroomlights");
        add("tag.item.chipped.sand", "Sand");
        add("tag.item.chipped.soul_sand", "Soul Sand");
        add("tag.item.chipped.crimson_roots", "Crimson Roots");
        add("tag.item.chipped.warped_roots", "Warped Roots");
        add("tag.item.chipped.dried_kelp_block", "Dried Kelp Blocks");
        add("tag.item.chipped.lily_pad", "Lily Pads");
        add("tag.item.chipped.nether_sprouts", "Nether Sprouts");
        add("tag.item.chipped.nether_wart_block", "Nether Wart Blocks");
        add("tag.item.chipped.pumpkin", "Pumpkins");
        add("tag.item.chipped.carved_pumpkin", "Carved Pumpkins");
        add("tag.item.chipped.jack_o_lantern", "Jack o' Lanterns");
        add("tag.item.chipped.vine", "Vines");
        add("tag.item.chipped.warped_wart_block", "Warped Wart Blocks");
        add("tag.item.chipped.crimson_fungus", "Crimson Fungus");
        add("tag.item.chipped.warped_fungus", "Warped Fungus");
        add("tag.item.chipped.acacia_planks", "Acacia Planks");
        add("tag.item.chipped.birch_planks", "Birch Planks");
        add("tag.item.chipped.dark_oak_planks", "Dark Oak Planks");
        add("tag.item.chipped.jungle_planks", "Jungle Planks");
        add("tag.item.chipped.mangrove_planks", "Mangrove Planks");
        add("tag.item.chipped.oak_planks", "Oak Planks");
        add("tag.item.chipped.spruce_planks", "Spruce Planks");
        add("tag.item.chipped.crimson_planks", "Crimson Planks");
        add("tag.item.chipped.warped_planks", "Warped Planks");
        add("tag.item.chipped.cherry_planks", "Cherry Planks");
        add("tag.item.chipped.bamboo_planks", "Bamboo Planks");
        add("tag.item.chipped.acacia_log", "Acacia Logs");
        add("tag.item.chipped.birch_log", "Birch Logs");
        add("tag.item.chipped.dark_oak_log", "Dark Oak Logs");
        add("tag.item.chipped.jungle_log", "Jungle Logs");
        add("tag.item.chipped.mangrove_log", "Mangrove Logs");
        add("tag.item.chipped.oak_log", "Oak Logs");
        add("tag.item.chipped.spruce_log", "Spruce Logs");
        add("tag.item.chipped.crimson_stem", "Crimson Stems");
        add("tag.item.chipped.warped_stem", "Warped Stems");
        add("tag.item.chipped.cherry_log", "Cherry Logs");
        add("tag.item.chipped.barrel", "Barrels");
        add("tag.item.chipped.bookshelf", "Bookshelves");
        add("tag.item.chipped.ladder", "Ladders");
        add("tag.item.chipped.stripped_acacia_log", "Stripped Acacia Logs");
        add("tag.item.chipped.stripped_birch_log", "Stripped Birch Logs");
        add("tag.item.chipped.stripped_dark_oak_log", "Stripped Dark Oak Logs");
        add("tag.item.chipped.stripped_jungle_log", "Stripped Jungle Logs");
        add("tag.item.chipped.stripped_mangrove_log", "Stripped Mangrove Logs");
        add("tag.item.chipped.stripped_oak_log", "Stripped Oak Logs");
        add("tag.item.chipped.stripped_spruce_log", "Stripped Spruce Logs");
        add("tag.item.chipped.stripped_warped_stem", "Stripped Warped Stems");
        add("tag.item.chipped.stripped_crimson_stem", "Stripped Crimson Stems");
        add("tag.item.chipped.stripped_cherry_log", "Stripped Cherry Logs");
        add("tag.item.chipped.acacia_door", "Acacia Doors");
        add("tag.item.chipped.birch_door", "Birch Doors");
        add("tag.item.chipped.dark_oak_door", "Dark Oak Doors");
        add("tag.item.chipped.jungle_door", "Jungle Doors");
        add("tag.item.chipped.mangrove_door", "Mangrove Doors");
        add("tag.item.chipped.oak_door", "Oak Doors");
        add("tag.item.chipped.spruce_door", "Spruce Doors");
        add("tag.item.chipped.crimson_door", "Crimson Doors");
        add("tag.item.chipped.warped_door", "Warped Doors");
        add("tag.item.chipped.cherry_door", "Cherry Doors");
        add("tag.item.chipped.bamboo_door", "Bamboo Doors");
        add("tag.item.chipped.acacia_trapdoor", "Acacia Trapdoors");
        add("tag.item.chipped.birch_trapdoor", "Birch Trapdoors");
        add("tag.item.chipped.dark_oak_trapdoor", "Dark Oak Trapdoors");
        add("tag.item.chipped.jungle_trapdoor", "Jungle Trapdoors");
        add("tag.item.chipped.mangrove_trapdoor", "Mangrove Trapdoors");
        add("tag.item.chipped.oak_trapdoor", "Oak Trapdoors");
        add("tag.item.chipped.spruce_trapdoor", "Spruce Trapdoors");
        add("tag.item.chipped.crimson_trapdoor", "Crimson Trapdoors");
        add("tag.item.chipped.warped_trapdoor", "Warped Trapdoors");
        add("tag.item.chipped.cherry_trapdoor", "Cherry Trapdoors");
        add("tag.item.chipped.bamboo_trapdoor", "Bamboo Trapdoors");
        add("tag.item.chipped.torch", "Torches");
        add("tag.item.chipped.glass_pane", "Glass Panes");
        add("tag.item.chipped.black_stained_glass", "Black Stained Glass");
        add("tag.item.chipped.black_stained_glass_pane", "Black Stained Glass Panes");
        add("tag.item.chipped.blue_stained_glass", "Blue Stained Glass");
        add("tag.item.chipped.blue_stained_glass_pane", "Blue Stained Glass Panes");
        add("tag.item.chipped.brown_stained_glass", "Brown Stained Glass");
        add("tag.item.chipped.brown_stained_glass_pane", "Brown Stained Glass Panes");
        add("tag.item.chipped.cyan_stained_glass", "Cyan Stained Glass");
        add("tag.item.chipped.cyan_stained_glass_pane", "Cyan Stained Glass Panes");
        add("tag.item.chipped.gray_stained_glass", "Gray Stained Glass");
        add("tag.item.chipped.gray_stained_glass_pane", "Gray Stained Glass Panes");
        add("tag.item.chipped.green_stained_glass", "Green Stained Glass");
        add("tag.item.chipped.green_stained_glass_pane", "Green Stained Glass Panes");
        add("tag.item.chipped.light_blue_stained_glass", "Light Blue Stained Glass");
        add("tag.item.chipped.light_blue_stained_glass_pane", "Light Blue Stained Glass Panes");
        add("tag.item.chipped.light_gray_stained_glass", "Light Gray Stained Glass");
        add("tag.item.chipped.light_gray_stained_glass_pane", "Light Gray Stained Glass Panes");
        add("tag.item.chipped.lime_stained_glass", "Lime Stained Glass");
        add("tag.item.chipped.lime_stained_glass_pane", "Lime Stained Glass Panes");
        add("tag.item.chipped.magenta_stained_glass", "Magenta Stained Glass");
        add("tag.item.chipped.magenta_stained_glass_pane", "Magenta Stained Glass Panes");
        add("tag.item.chipped.orange_stained_glass", "Orange Stained Glass");
        add("tag.item.chipped.orange_stained_glass_pane", "Orange Stained Glass Panes");
        add("tag.item.chipped.pink_stained_glass", "Pink Stained Glass");
        add("tag.item.chipped.pink_stained_glass_pane", "Pink Stained Glass Panes");
        add("tag.item.chipped.purple_stained_glass", "Purple Stained Glass");
        add("tag.item.chipped.purple_stained_glass_pane", "Purple Stained Glass Panes");
        add("tag.item.chipped.red_stained_glass", "Red Stained Glass");
        add("tag.item.chipped.red_stained_glass_pane", "Red Stained Glass Panes");
        add("tag.item.chipped.white_stained_glass", "White Stained Glass");
        add("tag.item.chipped.white_stained_glass_pane", "White Stained Glass Panes");
        add("tag.item.chipped.yellow_stained_glass", "Yellow Stained Glass");
        add("tag.item.chipped.yellow_stained_glass_pane", "Yellow Stained Glass Panes");
        add("tag.item.chipped.black_wool", "Black Wool");
        add("tag.item.chipped.blue_wool", "Blue Wool");
        add("tag.item.chipped.brown_wool", "Brown Wool");
        add("tag.item.chipped.cyan_wool", "Cyan Wool");
        add("tag.item.chipped.gray_wool", "Gray Wool");
        add("tag.item.chipped.green_wool", "Green Wool");
        add("tag.item.chipped.light_blue_wool", "Light Blue Wool");
        add("tag.item.chipped.light_gray_wool", "Light Gray Wool");
        add("tag.item.chipped.lime_wool", "Lime Wool");
        add("tag.item.chipped.magenta_wool", "Magenta Wool");
        add("tag.item.chipped.orange_wool", "Orange Wool");
        add("tag.item.chipped.pink_wool", "Pink Wool");
        add("tag.item.chipped.purple_wool", "Purple Wool");
        add("tag.item.chipped.red_wool", "Red Wool");
        add("tag.item.chipped.white_wool", "White Wool");
        add("tag.item.chipped.yellow_wool", "Yellow Wool");
        add("tag.item.chipped.black_carpet", "Black Carpets");
        add("tag.item.chipped.blue_carpet", "Blue Carpets");
        add("tag.item.chipped.brown_carpet", "Brown Carpets");
        add("tag.item.chipped.cyan_carpet", "Cyan Carpets");
        add("tag.item.chipped.gray_carpet", "Gray Carpets");
        add("tag.item.chipped.green_carpet", "Green Carpets");
        add("tag.item.chipped.light_blue_carpet", "Light Blue Carpets");
        add("tag.item.chipped.light_gray_carpet", "Light Gray Carpets");
        add("tag.item.chipped.lime_carpet", "Lime Carpets");
        add("tag.item.chipped.magenta_carpet", "Magenta Carpets");
        add("tag.item.chipped.orange_carpet", "Orange Carpets");
        add("tag.item.chipped.pink_carpet", "Pink Carpets");
        add("tag.item.chipped.purple_carpet", "Purple Carpets");
        add("tag.item.chipped.red_carpet", "Red Carpets");
        add("tag.item.chipped.white_carpet", "White Carpets");
        add("tag.item.chipped.yellow_carpet", "Yellow Carpets");
        add("tag.item.chipped.ancient_debris", "Ancient Debris");
        add("tag.item.chipped.andesite", "Andesite");
        add("tag.item.chipped.basalt", "Basalt");
        add("tag.item.chipped.blackstone", "Blackstone");
        add("tag.item.chipped.calcite", "Calcite");
        add("tag.item.chipped.cobblestone", "Cobblestone");
        add("tag.item.chipped.dark_prismarine", "Dark Prismarine");
        add("tag.item.chipped.deepslate", "Deepslate");
        add("tag.item.chipped.diorite", "Diorite");
        add("tag.item.chipped.dripstone_block", "Dripstone Block");
        add("tag.item.chipped.end_stone", "End Stone");
        add("tag.item.chipped.gilded_blackstone", "Gilded Blackstone");
        add("tag.item.chipped.granite", "Granite");
        add("tag.item.chipped.magma_block", "Magma Blocks");
        add("tag.item.chipped.mossy_cobblestone", "Mossy Cobblestone");
        add("tag.item.chipped.mossy_stone_bricks", "Mossy Stone Bricks");
        add("tag.item.chipped.nether_bricks", "Nether Bricks");
        add("tag.item.chipped.netherrack", "Netherrack");
        add("tag.item.chipped.obsidian", "Obsidian");
        add("tag.item.chipped.prismarine", "Prismarine");
        add("tag.item.chipped.purpur_block", "Purpur Blocks");
        add("tag.item.chipped.quartz_block", "Quartz Blocks");
        add("tag.item.chipped.raw_copper_block", "Raw Copper Blocks");
        add("tag.item.chipped.raw_gold_block", "Raw Gold Blocks");
        add("tag.item.chipped.raw_iron_block", "Raw Iron Blocks");
        add("tag.item.chipped.red_nether_bricks", "Red Nether Bricks");
        add("tag.item.chipped.red_sandstone", "Red Sandstone");
        add("tag.item.chipped.sandstone", "Sandstone");
        add("tag.item.chipped.stone", "Stone");
        add("tag.item.chipped.smooth_stone", "Smooth Stone");
        add("tag.item.chipped.tuff", "Tuff");
        add("tag.item.chipped.terracotta", "Terracotta");
        add("tag.item.chipped.black_terracotta", "Black Terracotta");
        add("tag.item.chipped.blue_terracotta", "Blue Terracotta");
        add("tag.item.chipped.brown_terracotta", "Brown Terracotta");
        add("tag.item.chipped.cyan_terracotta", "Cyan Terracotta");
        add("tag.item.chipped.gray_terracotta", "Gray Terracotta");
        add("tag.item.chipped.green_terracotta", "Green Terracotta");
        add("tag.item.chipped.light_blue_terracotta", "Light Blue Terracotta");
        add("tag.item.chipped.light_gray_terracotta", "Light Gray Terracotta");
        add("tag.item.chipped.lime_terracotta", "Lime Terracotta");
        add("tag.item.chipped.magenta_terracotta", "Magenta Terracotta");
        add("tag.item.chipped.orange_terracotta", "Orange Terracotta");
        add("tag.item.chipped.pink_terracotta", "Pink Terracotta");
        add("tag.item.chipped.purple_terracotta", "Purple Terracotta");
        add("tag.item.chipped.red_terracotta", "Red Terracotta");
        add("tag.item.chipped.white_terracotta", "White Terracotta");
        add("tag.item.chipped.yellow_terracotta", "Yellow Terracotta");
        add("tag.item.chipped.black_glazed_terracotta", "Black Glazed Terracotta");
        add("tag.item.chipped.blue_glazed_terracotta", "Blue Glazed Terracotta");
        add("tag.item.chipped.brown_glazed_terracotta", "Brown Glazed Terracotta");
        add("tag.item.chipped.cyan_glazed_terracotta", "Cyan Glazed Terracotta");
        add("tag.item.chipped.gray_glazed_terracotta", "Gray Glazed Terracotta");
        add("tag.item.chipped.green_glazed_terracotta", "Green Glazed Terracotta");
        add("tag.item.chipped.light_blue_glazed_terracotta", "Light Blue Glazed Terracotta");
        add("tag.item.chipped.light_gray_glazed_terracotta", "Light Gray Glazed Terracotta");
        add("tag.item.chipped.lime_glazed_terracotta", "Lime Glazed Terracotta");
        add("tag.item.chipped.magenta_glazed_terracotta", "Magenta Glazed Terracotta");
        add("tag.item.chipped.orange_glazed_terracotta", "Orange Glazed Terracotta");
        add("tag.item.chipped.pink_glazed_terracotta", "Pink Glazed Terracotta");
        add("tag.item.chipped.purple_glazed_terracotta", "Purple Glazed Terracotta");
        add("tag.item.chipped.red_glazed_terracotta", "Red Glazed Terracotta");
        add("tag.item.chipped.white_glazed_terracotta", "White Glazed Terracotta");
        add("tag.item.chipped.yellow_glazed_terracotta", "Yellow Glazed Terracotta");
        add("tag.item.chipped.black_concrete", "Black Concrete");
        add("tag.item.chipped.blue_concrete", "Blue Concrete");
        add("tag.item.chipped.brown_concrete", "Brown Concrete");
        add("tag.item.chipped.cyan_concrete", "Cyan Concrete");
        add("tag.item.chipped.gray_concrete", "Gray Concrete");
        add("tag.item.chipped.green_concrete", "Green Concrete");
        add("tag.item.chipped.light_blue_concrete", "Light Blue Concrete");
        add("tag.item.chipped.light_gray_concrete", "Light Gray Concrete");
        add("tag.item.chipped.lime_concrete", "Lime Concrete");
        add("tag.item.chipped.magenta_concrete", "Magenta Concrete");
        add("tag.item.chipped.orange_concrete", "Orange Concrete");
        add("tag.item.chipped.pink_concrete", "Pink Concrete");
        add("tag.item.chipped.purple_concrete", "Purple Concrete");
        add("tag.item.chipped.red_concrete", "Red Concrete");
        add("tag.item.chipped.white_concrete", "White Concrete");
        add("tag.item.chipped.yellow_concrete", "Yellow Concrete");
        add("tag.item.chipped.bricks", "Bricks");
        add("tag.item.chipped.borderless_bricks", "Borderless Bricks");
        add("tag.item.chipped.mud_bricks", "Mud Bricks");
        add("tag.item.chipped.pointed_dripstone", "Pointed Dripstone");
        add("tag.item.chipped.iron_bars", "Iron Bars");
        add("tag.item.chipped.sea_lantern", "Sea Lanterns");
        add("tag.item.chipped.redstone_lamp", "Redstone Lamps");
        add("tag.item.chipped.redstone_block", "Redstone Blocks");
        add("tag.item.chipped.lantern", "Lanterns");
        add("tag.item.chipped.soul_lantern", "Soul Lanterns");
        add("tag.item.chipped.special_lantern", "Special Lanterns");
        add("tag.item.chipped.special_soul_lantern", "Special Soul Lanterns");
        add("tag.item.chipped.redstone_torch", "Redstone Torches");
    }
}
